[project]
name = "nlp100-kobae964"
version = "2025.7.1"
requires-python = "==3.12.*"
dependencies = [
    "mecab ==0.996.5",
    "matplotlib ~=3.10",
    "cabocha-python ~= 0.69",
    "gensim ~= 4.3.2",
]
